---
title: "phytotraitr"
author: "Andrew M. Dolman"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---

A compilation of published phytoplankton trait data compilations. 

Contains:

* Nutrient uptake traits from Edwards et al (2015)
* Thermal traits from Chen (2015)

## Usage

```{r, echo=FALSE, message=FALSE}
library(knitr)
library(phytotraitr)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r tables, results='markup'}
#kable(Edwards_nutrient_traits[1:10,])
kable(Edwards_nutrient_traits_meta, format = "markdown")
kable(Chen_thermal_traits_meta, format = "markdown")
```

```{r, message=FALSE}
p <- Edwards_nutrient_traits %>% 
  ggplot(aes(x = taxon, y = `vmax_p`, fill = system, colour=system)) +
  geom_point(position = position_jitterdodge(jitter.width = 0.2)) + 
  coord_flip() +
  scale_y_continuous(trans = "log10")
p
```

```{r, message=FALSE, fig.height=12}
Edwards_nutrient_traits_long <- Edwards_nutrient_traits %>%
  select(-species, -isolate, -citation, -c_citation) %>% 
  gather(Group, Value, -taxon, - system, -temperature, -irradiance, -light_hours, -synonym) %>% 
  filter(complete.cases(Value)) %>% 
  mutate(Value = as.numeric(Value))

p <- Edwards_nutrient_traits_long %>% 
  ggplot(aes(x = Value)) +
  geom_histogram() + 
  facet_wrap(~Group, scales = "free_y", ncol = 4) +
  theme(aspect.ratio = 1) + 
  scale_x_continuous(trans = "log10")
p
```

```{r chen1}
p <- Chen_thermal_traits %>% 
  ggplot(aes(x = T_g_min, y=T_g_max)) %>% 
  +  geom_point(position = position_jitter(width = 0.2, height = 0.2))
p
```

